import {readFileSync,writeFileSync,mkdirSync,existsSync} from 'node:fs';
import ts from 'typescript';
import {DataUtils} from 'three';
import {createHash} from 'node:crypto';
const source=(p)=>readFileSync(new URL(p,import.meta.url),'utf8');
const compile=s=>ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const planSource=source('../lib/world/city-plan.ts'),assetSource=source('../lib/world/city-assets.ts');
const architectureSource=source('../lib/world/city-architecture.ts');
const fingerprint=createHash('sha256').update(planSource+assetSource+architectureSource+readFileSync(new URL(import.meta.url))).digest('hex').slice(0,12);
const root=new URL('../public/world/city/',import.meta.url);mkdirSync(root,{recursive:true});
const manifestPath=new URL('manifest.json',root);
writeFileSync(new URL('../lib/world/city-version.ts',import.meta.url),`// Generated by build-city.mjs.\nexport const CITY_ASSET_VERSION = '${fingerprint}';\n`);
if(existsSync(manifestPath)&&JSON.parse(readFileSync(manifestPath)).version===fingerprint){console.log('City assets unchanged.');process.exit(0)}
const planURL=url(compile(planSource));const plan=await import(planURL);
const {makeRegion}=await import(url(compile(assetSource).replace(/(['"])\.\/city-architecture\1/g,JSON.stringify(url(compile(architectureSource).replace(/(['"])\.\/city-plan\1/g,JSON.stringify(planURL))))).replace(/(['"])\.\/city-plan\1/g,JSON.stringify(planURL))));
const {CITY,terrainHeight,sampledRoads,streams}=plan;
// Store height + signed 16-bit X/Z normal components. Y is reconstructed positive.
// Offline slope sampling prevents hundreds of thousands of survey calls during first paint.
function terrainBuffer(heights,point){
 const count=heights.length,buffer=new ArrayBuffer(count*8);new Float32Array(buffer,0,count).set(heights);
 const normals=new Int16Array(buffer,count*4,count*2);
 for(let i=0;i<count;i++){const [x,z]=point(i),nx=terrainHeight(x-1,z)-terrainHeight(x+1,z),nz=terrainHeight(x,z-1)-terrainHeight(x,z+1),length=Math.hypot(nx,2,nz);normals[i*2]=Math.round(nx/length*32767);normals[i*2+1]=Math.round(nz/length*32767);}
 return Buffer.from(buffer);
}
const tiles=[];
for(let iz=0;iz<CITY.depth/CITY.tile;iz++)for(let ix=0;ix<CITY.width/CITY.tile;ix++){
 const x=-CITY.width/2+ix*CITY.tile,z=-CITY.depth/2+iz*CITY.tile;
 for(const n of [16,32,64]){const data=new Float32Array((n+1)**2);for(let j=0;j<=n;j++)for(let i=0;i<=n;i++)data[j*(n+1)+i]=terrainHeight(x+i*256/n,z+j*256/n);writeFileSync(new URL(`${ix}-${iz}-${n}.bin`,root),terrainBuffer(data,i=>[x+(i%(n+1))*256/n,z+Math.floor(i/(n+1))*256/n]))}
 tiles.push({id:`${ix}-${iz}`,x,z});
}
const far=new Float32Array(113*81);for(let j=0;j<=80;j++)for(let i=0;i<=112;i++)far[j*113+i]=terrainHeight(-3584+i*64,-2560+j*64)-.8;
writeFileSync(new URL('far.bin',root),terrainBuffer(far,i=>[-3584+(i%113)*64,-2560+Math.floor(i/113)*64]));
const water=new Uint16Array(512*512);for(let j=0;j<512;j++)for(let i=0;i<512;i++)water[j*512+i]=DataUtils.toHalfFloat(terrainHeight(-3584+i/511*7168,-2560+j/511*5120));writeFileSync(new URL('water.bin',root),Buffer.from(water.buffer));
for(const region of ['town','commons','airport','arrival','works','dive','archive','station','nature']){const parts=makeRegion(region);writeFileSync(new URL(region+'.json',root),JSON.stringify(parts));const far=region==='nature'?parts.filter((_,i)=>Math.floor(i/2)%3===0).map(p=>p[0]===6?[2,...p.slice(1)]:p):parts.filter(p=>p[5]*p[7]>180);writeFileSync(new URL(region+'-far.json',root),JSON.stringify(far));}
writeFileSync(manifestPath,JSON.stringify({version:fingerprint,tiles}));
const point=(x,z)=>[640+x*.15,420+z*.135];
let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 800" role="img" aria-label="Island districts, airport and harbours"><rect width="1280" height="800" fill="#477b89"/>';
for(let j=0;j<80;j++)for(let i=0;i<112;i++){const x=-3584+i*64,z=-2560+j*64,h=far[j*113+i];if(h<0)continue;const [px,py]=point(x,z);svg+=`<rect x="${px}" y="${py}" width="10" height="9" fill="${h>60?'#789173':h>25?'#93b578':'#b4cb92'}"/>`}
for(const s of streams)svg+=`<polyline points="${s.map(p=>point(p[0],p[2]).join(',')).join(' ')}" fill="none" stroke="#77b1b0" stroke-width="4"/>`;
for(const r of sampledRoads)svg+=`<polyline points="${r.points.map(p=>point(p[0],p[2]).join(',')).join(' ')}" fill="none" stroke="#eeeada" stroke-width="2"/>`;
for(const [id,p] of Object.entries(plan.sites)){const [x,z]=point(p[0],p[2]);svg+=`<circle cx="${x}" cy="${z}" r="5" fill="#f3efe4"/><text x="${x+9}" y="${z+4}" font-family="sans-serif" font-size="13" fill="#18363d">${id}</text>`}
svg+='</svg>';writeFileSync(new URL('../procedural-map.svg',root),svg);
console.log(`Generated ${tiles.length} terrain tiles × 3 LODs and 9 regions (${fingerprint}).`);
